name: NuGet-Deploy-Preview

on:
  workflow_dispatch:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+-preview[0-9][0-9][0-9][0-9]-[0-1][0-9]-[0-3][0-9]"
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'

env: 
    NUGET_KEY: ${{ secrets.NUGET_API_KEY }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${VERSION} --output .
    - name: Push
      run: dotnet nuget push SmartishTable.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key $NUGET_KEY
      #uses: brandedoutcast/publish-nuget@v2.5.2
      #with:
      #    PROJECT_FILE_PATH: src/SmartishTable/SmartishTable.csproj
      #    NUGET_KEY: ${{secrets.NUGET_API_KEY}}
